### ISSUE TITLE
OpenBodyCams compatibility + Config settings

### ISSUE THREAD

**Issue by thundershocker1** [xntkrnl/CruiserTerminal_NET2.1#1]
Hey. Amazing mod! I was wondering if you'd be working on compatibility with OpenBodyCams, as well as allowing for us to configure the mod. One thing I was looking for is to make the screen bigger, as since I have the resolution set to low, the text isn't legible. Another thing was to make the angle at which we look at the console not angled, but that is something you could allow of us to configure.

If you don't mind, I'd love for you to create a post within this discord so people can better communicate any issues they're facing

https://discord.com/channels/1168655651455639582/1169056298856362105

**Comment by xntkrnl** [comment]
Hi, thanks for your feedback.
First: the terminal's "screen resolution" is exactly the same as the ship's terminal.

Second: I agree about the player's view and the screen not being aligned (because of this the text is not very clear, I will fix this in the future).

Third: the post has already been created, it is listed in the mod description
![image](https://github.com/user-attachments/assets/1ed3aa58-24be-46e7-80e8-db6e7c40891f)


Edit: OpenBodyCams has a command for the terminal that allows you to watch from the target's point of view from the terminal
