### ISSUE TITLE
I only see the top of the Screen.

### ISSUE THREAD

**Issue by VanilaBOI** [xntkrnl/CruiserTerminal_NET2.1#2]
I don't know which mod is causing this but no matter what orientation the cruiser is, I only see this:
![20241024154645_1](https://github.com/user-attachments/assets/4fc9ffc0-4bd5-4543-8a83-09e5b2d395eb)

MODPACK CODE: 0192bec9-f0bd-629c-0844-2f700aa2c0e6

**Comment by xntkrnl** [comment]
Hi, thanks for a feedback
your mods are super old, some of them can't even be downloaded (because they were deleted from thunderstore), so I can't help you

Edit: At first I didn't understand that advanced company needs its own version of r2modman, opened issue again

Edit2: still can't download it, sorry

**Comment by VanilaBOI** [comment]
I totally get it If you don't want to add compatibility for advanced company but when I disable advanced company, I still get this view.

**Comment by xntkrnl** [comment]
the problem is not whether I want or don't want to make compatibility with advanced company (it's not even required judging by your message), but whether I can do it now and whether I can download the modpack
I downloaded the forked modman but the modpack still didn't want to be installed
